CREATE DATABASE tienda;
USE tienda;
CREATE TABLE usuario(
ID SMALLINT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(255) NOT NULL,
CORREO VARCHAR(255) NOT NULL,
TELEFONO BIGINT NOT NULL, 
EDAD SMALLINT,
CHECK(EDAD >= 18 and EDAD < 90)
);

SELECT * FROM usuario;